name: program-downloader

on:
  push:
  workflow_dispatch:

jobs:
  build:
    container:
      image: mcr.microsoft.com/playwright:v1.51.0-jammy
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        uses: check-spelling-sandbox/refactored-octo-train@16cd1fac19630ad6fbdb198f0ab4e3cc4c3b7603
        with:
          repository: cli/cli
          destination: ../bin/gh
          file-re: bin/b
          add-to-path: 1
          trace: 1

      - name: Run a one-line script
        run: |
          (
            echo "gh: $(command -v gh)"
            echo "../bin:"
            find ../bin || true
          )| tee -a "$GITHUB_STEP_SUMMARY"
